[supabase]
url = "https://fdicdpnrhggbghquiyne.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkaWNkcG5yaGdnYmdocXVpeW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjI4ODEsImV4cCI6MjA2OTUzODg4MX0.uVGvV5p7je4He5-kuhTy3bcLovk6gOeRgTxCxvK7Spo"
